### PR TITLE
fix(client): load more button disappears after reach the maximum - PST-107

### PR DESCRIPTION
**Pull request by duaakelzi**
the load more disappear when reaching the last page or reach the maximum that is provided by the API which is 2000 results try:

1. water+hunger
2. bread+grain
3. bread : for the maximum

### CODE REVIEW

**Review by samuelhuebner — CHANGES_REQUESTED** [review]
For me the load more button still is not disappearing after reaching the last page

**Review by AlbinaMuzafarova — COMMENTED** [review]
@duaakelzi I'm getting an error, requesting page 14 for "bread+grain". I suppose because results 1301-1400 don't exist. The button is there.

**Comment by duaakelzi** [comment]
ok guys i will fix it @AlbinaMuzafarova  @samuelhuebner

**Comment by duaakelzi** [comment]
a question for Albina why you changed the PST number in the commit message? @AlbinaMuzafarova

**Comment by AlbinaMuzafarova** [comment]
@duaakelzi as far as I remember, there was no pst indicated in the PR (maybe because the message was too long). Since the PR had no description and title was cut off, i didn't know what to test for and what the ticket was about. So i looked it up in jira and added the pst number so that others didn't have to look it up as well. 

I'm sorry if it had messed up the commit message for you

**Comment by duaakelzi** [comment]
no i am fine with changing but just because it was wrong it is PST-107 not PST-170

**Comment by AlbinaMuzafarova** [comment]
yes, I just noticed that I mistyped. Sorry!

**Comment by samuelhuebner** [comment]
> @duaakelzi as far as I remember, there was no pst indicated in the PR (maybe because the message was too long). Since the PR had no description and title was cut off, i didn't know what to test for and what the ticket was about. So i looked it up in jira and added the pst number so that others didn't have to look it up as well.
> 
> I'm sorry if it had messed up the commit message for you
> 
> PS: just noticed that I typed 170 instead of 107. Sorry!

I think that only changed the title of the PR 🙂  @AlbinaMuzafarova @duaakelzi

**Comment by duaakelzi** [comment]
yes you are right i didn't recognize that also sorry i just woke up @samuelhuebner

**Comment by duaakelzi** [comment]
just a remark the error that albina got not because of my changes it is a server error not depending on the result count @AlbinaMuzafarova @samuelhuebner

**Comment by samuelhuebner** [comment]
> just a remark the error that albina got not because of my changes it is a server error not depending on the result count @AlbinaMuzafarova @samuelhuebner

Yes that's true because a page is requested that is not available. But the goal of this ticket is to prevent the user from doing exactly that.

**Comment by duaakelzi** [comment]
yes i realized that and deleted my comment i will fix that @samuelhuebner

**Comment by duaakelzi** [comment]
can you try now @AlbinaMuzafarova  @samuelhuebner

**Comment by AlbinaMuzafarova** [comment]
i'm afraid it's still the same on my side. 

keywords: lighthouse, energy

range: 201-300 gives error, button still there

**Comment by duaakelzi** [comment]
did you pull the last changes because it is working for me with your keywords i got only one time load more @AlbinaMuzafarova

**Review by AlbinaMuzafarova — APPROVED** [review]
you are right @duaakelzi ! it works well with latest changes, well done!

**Review by samuelhuebner — APPROVED** [review]

**Pull request merged**
