### PR TITLE
feat(client): Add about page - PST-189

### PR DESCRIPTION
**Pull request by samuelhuebner**
- Adds an about page with a short description (can be changed if someone has a better idea)
- Adds Contributors to about page (order is shuffled on each refresh)

### CODE REVIEW

**Comment by fiordidoma** [comment]
Looks pretty nice to me. Well done!

**Comment by samuelhuebner** [comment]
> Looks pretty nice to me. Well done! Edit: There is also a vector version of the THU logo: https://studium.hs-ulm.de/_catalogs/masterpage/HSUlm/images/logo.svg You might consider changing it.

Any specific reason for using .svg in this scenario? Otherwise I would leave It as is, since it's already done

**Comment by fiordidoma** [comment]
> 
> 
> > Looks pretty nice to me. Well done! Edit: There is also a vector version of the THU logo: https://studium.hs-ulm.de/_catalogs/masterpage/HSUlm/images/logo.svg You might consider changing it.
> 
> Any specific reason for using .svg in this scenario? Otherwise I would leave It as is, since it's already done

Not necessarily, just that it would be nicer I guess.

**Comment by samuelhuebner** [comment]
> > > Looks pretty nice to me. Well done! Edit: There is also a vector version of the THU logo: https://studium.hs-ulm.de/_catalogs/masterpage/HSUlm/images/logo.svg You might consider changing it.
> > 
> > 
> > Any specific reason for using .svg in this scenario? Otherwise I would leave It as is, since it's already done
> 
> Not necessarily, just that it would be nicer I guess.

In what way nicer? 😅  Would look exactly the same since the png has also a transparent background. The svg would make sense if we wanted to scale the logo but it is rather small so I think it won't make any difference.

**Review by micahh2 — COMMENTED** [review]
I know this is a strange request, but I'd greatly prefer if my full name wasn't included on this page.

**Review by AlbinaMuzafarova — APPROVED** [review]
looks good to me, thanks Samuel!

**Review by micahh2 — APPROVED** [review]
Looks good!

**Pull request merged**
