### PR TITLE
Feature/functionalities detailed patent view - PST-103

### PR DESCRIPTION
**Pull request by duaakelzi**
two functionalities implemented : save the patent using the detailedPatentView and see the patent in completely new page

### CODE REVIEW

**Review by samuelhuebner — COMMENTED** [review]
So far it looks good 👍🏼 thank you @duaakelzi  

I have some small remarks though:
- The "done" button has the functionality to open the patent view. I think it would be more clear to move this to the "open_in_new" button and remove the "done" button 
- The search term chips are missing on the detailed view
- The inventors/applicant - headings are a little bit off from the actual list
- The exploration button could also show up in the patent view
- Scrollbars are showing up in the patent view. You can fix this by adding `width: 90vw;` to the `.attachments` css selector.
- The open in new page functionality could also exist on the saved page 
- The saved icon is not present on the patent page

**Review by icicala — COMMENTED** [review]
Thank You @duaakelzi. How we were discussed now the explore button makes more sense for me.
The exploration button should be in the centre down by design or should be the bottom right? 
image

**Comment by samuelhuebner** [comment]
Thank you for the enhancements @duaakelzi 👍🏼 

I noticed some new issues:
- Layout of the exploration button is broken:
image

- When refreshing the page the search terms of the URL-query are not applied anymore

- There should be a little bit of spacing on the bottom because right now for patents with a lot of content its looks off:
image

**Comment by duaakelzi** [comment]
i fixed the issued but about URL i am not sure because it is working from my side @samuelhuebner

**Comment by AlbinaMuzafarova** [comment]
@duaakelzi upon refresh on the full-screen patent preview, i get an error on the console:

image

can you replicate it?

**Comment by samuelhuebner** [comment]
> i fixed the issues but about URL i am not sure because it is working from my side @samuelhuebner

@duaakelzi I added a fix for the URL. It would appear when opening a saved patent on the Patent page which had other search terms than the current search. From my point of view it looks good now 👍🏼

**Review by samuelhuebner — APPROVED** [review]

**Comment by duaakelzi** [comment]
> > i fixed the issues but about URL i am not sure because it is working from my side @samuelhuebner
> 
> @duaakelzi I added a fix for the URL. It would appear when opening a saved patent on the Patent page which had other search terms than the current search. From my point of view it looks good now 👍🏼

thank you Samu i will wait another reviews then merge it @samuelhuebner

**Review by AlbinaMuzafarova — APPROVED** [review]
thanks, Duaa! the error is gone now!

**Comment by duaakelzi** [comment]
nice i will merge then @AlbinaMuzafarova

**Pull request merged**
