### PR TITLE
Feature/exploration page - PST-155

### PR DESCRIPTION
**Pull request by samuelhuebner**
This adds a new "Exploration" page for patents, accessable via the "Start exploration" Button. Currently the exploration page shows patents belonging to the same family

Note: Not every patent gets results for the patent family request. So only for patents with an available patent family the button will be shown

### CODE REVIEW

**Review by duaakelzi — APPROVED** [review]
i like it good job Samu thank you

**Review by icicala — COMMENTED** [review]
Amazing! Everything is working perfectly except on things. I am sure You know about it.
The patent which doesn't have documents in the console is throwing an error. Should be ignored at this point?
image

**Comment by samuelhuebner** [comment]
> Amazing! Everything is working perfectly except on things. I am sure You know about it. The patent which doesn't have documents in the console is throwing an error. Should be ignored at this point? image

@icicala The error is not thrown but rather logged. When no family / document(s) is available the backend throws a Not found error which I then catch and log out into the console with `console.error(err).` If you don't like that i can omit the logging of the error. But it's not really doing any harm there

**Review by AlbinaMuzafarova — APPROVED** [review]
works well on my side, too! Finally the exploration mode receives attention :) 

A few remarks:

- I was wondering whether "Patents in same family" would be a more explicit title. Maybe for the user group, "Family" is enough though. 
- As we have discussed, it maybe unnecessary to list the target patent again in family. But that's again up for the client. Maybe for them it makes more sense to see all together
- The Family button looks a bit off for me but that's most likely a firefox issue again

**Comment by icicala** [comment]
> > Amazing! Everything is working perfectly except on things. I am sure You know about it. The patent which doesn't have documents in the console is throwing an error. Should be ignored at this point? image
> 
> @icicala The error is not thrown but rather logged. When no family / document(s) is available the backend throws a Not found error which I then catch and log out into the console with `console.error(err).` If you don't like that i can omit the logging of the error. But it's not really doing any harm there

oooh sorry! I didn't notice it at the first time. It is perfect! Danke!

**Review by icicala — APPROVED** [review]
Works Perfect! I like it very much! Thank You @samuelhuebner for your great contribution.

**Comment by micahh2** [comment]
This looks great! I'm blown away @samuelhuebner 

I don't think we really need to address this potential issue but I did want to mention one thing:

In firefox (I know, I know) the "family" chip in the divider is clipped. I've found changing the chip styles to use `width: fit-content` instead of `max-width: fit-content` fixes this (and also fixes another firefox bug in the search bar) 
image

Great job. :+1:

**Review by micahh2 — APPROVED** [review]

**Comment by samuelhuebner** [comment]
> This looks great! I'm blown away @samuelhuebner
> 
> I don't think we really need to address this potential issue but I did want to mention one thing:
> 
> In firefox (I know, I know) the "family" chip in the divider is clipped. I've found changing the chip styles to use `width: fit-content` instead of `max-width: fit-content` fixes this (and also fixes another firefox bug in the search bar) image
> 
> Great job. 👍

Thanks for pointing that out 👍🏼

**Pull request merged**
