### PR TITLE
Add citation preview box on click - PST-153

### PR DESCRIPTION
**Pull request by micahh2**
Let me know if you guys want different design / functionality. I tried to put something together that could be quickly replicated for the other node types.

### CODE REVIEW

**Review by duaakelzi — APPROVED** [review]
i think it is nice not sure but i think we don't have more information to display

**Review by samuelhuebner — APPROVED** [review]
I like the design of citations preview 👍🏼 

Just two minor points:
- I think a little bit more spacing between the Heading and "Cited by" would be nice
- We don't really have borders in our design yet, maybe you could change the border on the  patents to have no border but rather a box-shadow just like the rest of our design to have a little bit more consistency.

Other than that I like the feature. Good job 👍🏼

**Review by AlbinaMuzafarova — APPROVED** [review]
I like the preview box, thanks Micah! It's also nice to see the preview of the patent listed there on a click! And the back/forward arrows work too! 

With the citation box available, seems like the "No Data" could be changed to "No title" in the tooltip, otherwise looks contradictory... Not sure it would go within the scope of this PR though

**Comment by micahh2** [comment]
Thank you all for the reviews!

@samuelhuebner Good point about the styling, I've updated it to use the box-shadow and increased the margin between the "Cited By"
@AlbinaMuzafarova I've updated the tooltip text to have the "CITATION" + the id. Though, I can change it to something else if that's weird for people

**Comment by samuelhuebner** [comment]
> Thank you all for the reviews!
> 
> @samuelhuebner Good point about the styling, I've updated it to use the box-shadow and increased the margin between the "Cited By" @AlbinaMuzafarova I've updated the tooltip text to have the "CITATION" + the id. Though, I can change it to something else if that's weird for people

@micahh2 very nice. One 'more' thing. Maybe it would be even more consistent to use our global 'box-shadow' class for the shadow. Then it should be the same as e.g. in the search bar 🙂

**Pull request merged**
