### PR TITLE
Add family nodes / links to main visualization - PST-120

### PR DESCRIPTION
**Pull request by micahh2**
This one will require some group feedback. There aren't that many family ties being brought back in the average search, so It's not clear if this will be that important.

If it's desired we can skip the family nodes and just directly connect patents in the same family, but personally I think the family nodes are nice.

I've found including the term 'family' tends to lead to some families being shown in the results, but I'm sure there's lots of better terms out there.

### CODE REVIEW

**Comment by AlbinaMuzafarova** [comment]
thank you Micah! 

I like to see the family nodes on the graph although it is really a pity that it's so few of them. I'd not connect the patents directly because the family title might be interesting to user and this data might get lost if there're no specific nodes for families. 

 My first thought when i saw a family node was "who else is there?".  Perhaps user would also want to see the full scope of patents belonging to the family.. If there were patents that were filtered out because they don't meet the keywords, we could probably make use of the exploration button to show all nodes (matching/not matching keywords) in that specific family. Not sure if that's of high importance to the client though..

**Comment by samuelhuebner** [comment]
I think visualizing them as nodes is a good approach @micahh2 👍🏼 . Maybe we could add an option to the options menu with the same color though which is turned on by default. So that the user has some info what this node represents. Since they have a relatively similar color and are also not that often present I didn't notice the family nodes at first.

**Review by duaakelzi — COMMENTED** [review]
i like the family node but as Samu said it doesn't really clear to the user what this node represent maybe we can find a better approach

**Review by icicala — COMMENTED** [review]
The idea to show the family patents is great. I like your approach @micahh2. I was thinking about if it makes sense here to colour the nodes of that specific family in the same colour. In this case, easily we can distinguish between different families. 
image

**Comment by fiordidoma** [comment]
Well done @micahh2! I am also in for a "family" toggle switch on the options menu.

**Comment by micahh2** [comment]
Alright, I've added a toggle switch to the options menu.

**Comment by samuelhuebner** [comment]
> Alright, I've added a toggle switch to the options menu.

Not sure if that's a chrome issue but the label for the families isn't showing up:
image

**Comment by micahh2** [comment]
@samuelhuebner Wow, I can definitely be blind sometimes! This should look a little better hopefully.

**Review by samuelhuebner — APPROVED** [review]
@micahh2 Now everything shows up as it should do 👍🏼

**Review by AlbinaMuzafarova — APPROVED** [review]
looks good on my side, too! thanks Micah!

**Review by icicala — COMMENTED** [review]
@micahh2 Do you find a better way to change the colour of a family node in another one? I don't have a good vision here but the family node makes me think that is another patent node somehow. Can be because of old screen :)))

**Comment by micahh2** [comment]
I've changed the color to purple! If that's not a color that people are interested in (or if it's too similar to blue or red) let me know.

**Comment by AlbinaMuzafarova** [comment]
good that our client is not color-blind! :)

**Pull request merged**
