### PR TITLE
Feature/extend exploration - PST-80

### PR DESCRIPTION
**Pull request by samuelhuebner**
This is a rather big merge request that introduces following changes:

- Centers cards inside of the exploration mode
- Adapts divider-chip colors
- Adds Citations to exploration mode
- Adds Inventor patents to exploration mode
- Adds Applicant patents to exploration mode
- Add saving of patents from exploration mode
- Add minimum loading screen time to have a more 
- Add loading screen to view changes

### CODE REVIEW

**Comment by fiordidoma** [comment]
Very nice work Samuel! Well done and thank you!

**Review by duaakelzi — APPROVED** [review]
very good work thank you Samu

**Review by AlbinaMuzafarova — APPROVED** [review]
thank you Samuel, looks great! 

Are citations embedded inside Family or supposed to be distinguished like Authors/Companies?
I am getting family cards all with same title and similar abstracts in Family. Depending on client's feedback, maybe an explanation for that would be needed since user might not be aware that they all have different IDs

image

**Review by icicala — APPROVED** [review]
Well done! Thank You indeed for Your contribution.

**Comment by samuelhuebner** [comment]
Added the onSave handler for the detailed patent view @icicala

**Comment by samuelhuebner** [comment]
> thank you Samuel, looks great!
> 
> Are citations embedded inside Family or supposed to be distinguished like Authors/Companies? I am getting family cards all with same title and similar abstracts in Family. Depending on client's feedback, maybe an explanation for that would be needed since user might not be aware that they all have different IDs
> 
> image

Yes that's true. Some family cards returned by the family endpoiont from ops are indeed the same patent. I am not sure why this is.

**Review by micahh2 — APPROVED** [review]
This looks awesome.

**Pull request merged**
