### PR TITLE
Feature/add companies authors visualization PST-128 PST-129

### PR DESCRIPTION
**Pull request by icicala**
Add real companies in visualization PST-129
Add real authors in visualization PST-128
The company and authors are added to the graph, thanks to the great help and contribution of @samuelhuebner.
Now you can filter accordingly and see the real author and company on nodes.

### CODE REVIEW

**Review by samuelhuebner — APPROVED** [review]
Works for me! Thank you @icicala 
image

**Comment by icicala** [comment]
> Works for me! Thank you @icicala image

@samuelhuebner Thank You indeed for your great help and contribution.

**Review by duaakelzi — APPROVED** [review]
worked for me thank you Ion!

**Review by AlbinaMuzafarova — APPROVED** [review]
works for me, too, thanks @icicala !

**Pull request merged**
