### PR TITLE
feat(server): add mock search endpoint (PST-17)

### PR DESCRIPTION
**Pull request by micahh2**

### CODE REVIEW

**Comment by samuelhuebner** [comment]
Also:
The logic for the `/patents` endpoint should be contained in its own module for better modularization. You can get more infos on nestjs modules [here](https://docs.nestjs.com/modules)

**Comment by samuelhuebner** [comment]
@micahh2 Your commit message is still missing something.

**Comment by micahh2** [comment]
@samuelhuebner Sounds like you would like to do this card. I'll just close this one and send it back for rework, I can work on something else. :+1:

**Comment by samuelhuebner** [comment]
Actually I was just reviewing your changes. But I am fine with you working on something else 👍🏼

**Pull request closed without merging**
