### PR TITLE
Show citations when node is selected - PST-65

### PR DESCRIPTION
**Pull request by micahh2**

### CODE REVIEW

**Review by samuelhuebner — CHANGES_REQUESTED** [review]
Citations show up after clicking a patent node 👍🏼 I have some remarks/issues though:

- The patent preview doesn't show up anymore
- The simulation is restarted always with a high alpha value which causes nodes to be thrown around after each click
- The simulation is also restarted if the node has no citations which causes the simulation to be restarted for no reason

**Review by duaakelzi — COMMENTED** [review]
Thank you Micah the citations work perfectly but like what Samu said about the patentPreview and the simulation if you can fix them before merging

**Review by AlbinaMuzafarova — APPROVED** [review]
thank you Micah, it's fun to click on patents/citations and get additional ones!

**Comment by micahh2** [comment]
Thank you all for the great reviews! I've lowered the alpha value on click so things don't move around so much.

Regarding the patent preview disappearing after clicking on a citation, that's an issue that is reproducible on Main and I believe was introduced with the refactor.

**Review by samuelhuebner — APPROVED** [review]

**Comment by micahh2** [comment]
@samuelhuebner  I'm not certain I agree with your changes, and how you just skipped review by pushing them into my branch...

**Comment by samuelhuebner** [comment]
> @samuelhuebner I'm not certain I agree with your changes, and how you just skipped review by pushing them into my branch...

@micahh2 Oh sorry. From your now deleted comment I figured that you didn't really think that the bugfix was in scope for your ticket and that's why i already cherry picked the fix we created for this behaviour from Ions branch into yours on my machine. Since your branch would be the first to be merged into main I had the impression it would be best to have the same behaviour on both branches. After I cherry picked the fix I saw that you already pushed almost the same fix and removed the comment mentioning that this was already broken in main.  That's why i added the "missing" line to your branch since its directly related to the issue at hand.

**Comment by micahh2** [comment]
@samuelhuebner Okay, that makes a lot more sense. The reason I didn't address it initially is that we really need a card surrounding displaying citation/other previews, and I figured the fix would work better there. But then I decided it would be easier to half fix it than to explain my reasoning about more work being really required for it to be "properly fixed". 
Good work :+1:

**Comment by samuelhuebner** [comment]
@micahh2 Yeah the proper fix might involve loading the data for this patent from OPS. So that the patent preview would show the cited-patent information. 

Also regarding me merging your pull request. I wasn't sure when you would come to merge it and I thought it would be nice to have the citations also deployed for the meeting with graf&balser so that we can show that we have progress. And In any other case I would have left this for you to do. Hope that's okay 👍🏼

**Pull request merged**
