### PR TITLE
refactor(client): Refactor option menu to be responsive on click away…

### PR DESCRIPTION
**Pull request by icicala**
… - PST-187

The options menu is responsive on click away.

### CODE REVIEW

**Comment by samuelhuebner** [comment]
Does the job for me 👍🏼 . Although I saw that you removed the timer option. I think it would be nice to keep it since it's kind of a convenient feature. Maybe you can increase the time to 8-10seconds? So that it closes automatically after a longer time period.

**Review by AlbinaMuzafarova — APPROVED** [review]
thanks Ion, optionsmenu closes on clickaway with filters and togglers applied!

**Review by micahh2 — APPROVED** [review]
Looks great @icicala. I have notices that when I start adding a filter (add an empty filter) it takes two away clicks to close the overall option menu. I think getting rid of the timer entirely is reasonable enough as it's easy to close this menu now, and seemingly unlikely that someone will be annoyed by it being open when they want it closed. That being said, I'm sure It's also a matter of taste.

**Review by samuelhuebner — APPROVED** [review]
very nice 👍🏼

**Pull request merged**
