### PR TITLE
feature(client): make patentPreview movable - PST-132

### PR DESCRIPTION
**Pull request by duaakelzi**

### CODE REVIEW

**Review by icicala — COMMENTED** [review]
@Samu for the smaller screen the patent view movable is changing the div the text appears after the arrow next and back.
image

**Review by AlbinaMuzafarova — APPROVED** [review]
it is movable! thanks Duaa! 

It terms of design, I liked the size of the previous card a bit more - it was more compact. Have the feeling user would want to save the extra space for seeing as much of the visualization as possible :)

**Comment by samuelhuebner** [comment]
> it is movable! thanks Duaa!
> 
> It terms of design, I liked the size of the previous card a bit more - it was more compact. Have the feeling user would want to save the extra space for seeing as much of the visualization as possible :)

Since the blur is now removed from the patent preview it should look a lot more like before. Could you check again @AlbinaMuzafarova ?

**Review by samuelhuebner — APPROVED** [review]
Thank you duaa 👍🏼 . Patent preview is movable now

**Comment by AlbinaMuzafarova** [comment]
@samuelhuebner I'd keep the dimensions same as in the old preview card. The new preview uses too much space without necessarily needing it (see screenshot below). While for extended/detailed preview that's fine, the short preview card could be smaller in height like the old version. Hope this makes my previous comment clearer :)

image

**Pull request merged**
