### PR TITLE
fix(client): do not go back to landing page if there are no results - PST-135

### PR DESCRIPTION
**Pull request by duaakelzi**
… keyword - PST-135

### CODE REVIEW

**Review by AlbinaMuzafarova — APPROVED** [review]
Looks good to me. No redirect in case of 500 or 400 errors. Thanks Duaa!

**Review by micahh2 — CHANGES_REQUESTED** [review]
All the code changes look great. I think you just accidentally commited changes to package.json and package-lock.json  (Which probably shouldn't be there)
I think these commands to fix that: 
> git checkout origin/main -- client/package.json
> git checkout origin/main -- client/package-lock.json

**Review by icicala — APPROVED** [review]
I find this behaviour more intuitive to stay on the result page. Thank You Duaa for your contribution, well done!

**Review by samuelhuebner — APPROVED** [review]
Works for me. Good job Duaa 👍🏼

**Review by micahh2 — APPROVED** [review]

**Pull request merged**
