### PR TITLE
Save state to localstorage - PST-108

### PR DESCRIPTION
**Pull request by micahh2**

### CODE REVIEW

**Review by icicala — APPROVED** [review]
The state of the toggles filter, the saved patent and the additional filters are restored successfully after refreshing the page. 
I have just a question for the whole team if the filtered data (toggle and add filters) should keep the states in case of a new search by removing all the keywords and inserting others, or can be redefined after starting a new search. I have a feeling that on the new search the whole filter states should be erased. I have tested some edge cases, the states are restored successfully.  Danke Micah for your great contribution.

**Review by samuelhuebner — CHANGES_REQUESTED** [review]
Persisting the vuex store works 👍🏼 . 

As @icicala mentioned it is somewhat weird to have keywords, filters and settings being persisted after closing the tab or going back to the landing page. But on the other hand we need to store this information so that it isn't lost after a refresh of e.g. the saved page. Maybe clearing keywords & filters & settings on loading the "start"-page could work for now? 

In general it would make sense to move this info to the URL as query parameters so that a customer would be able to share a link to a search containing filters & search related settings. But that is out of scope for this ticket.

**Comment by micahh2** [comment]
@icicala Thanks for your feedback, I've updated this branch so that it clears the state when loading the start page. 

@samuelhuebner I agree that it would be nice to have this in the URL instead, but the card this PR is addressing was very explicitly about saving the state to localstorage...

**Comment by samuelhuebner** [comment]
> @icicala Thanks for your feedback, I've updated this branch so that it clears the state when loading the start page.
> 
> @samuelhuebner I agree that it would be nice to have this in the URL instead, but the card this PR is addressing was very explicitly about saving the state to localstorage...

@micahh2 Wasn't really a criticism but rather a thought that I had when reviewing your change. I think it's a good thing to have the store saved in local storage and especially the saved list needs to be in there. 👍🏼 

Regarding your latest change: Could you don't clear the entire state but rather only the keywords, filters and settings? I think it would be nice to at least persist the saved page.

**Review by AlbinaMuzafarova — APPROVED** [review]
Looks good to me: states persisted on refresh and cleared once thrown back to the start page due to error. Thanks Micah!

**Review by samuelhuebner — APPROVED** [review]

**Pull request merged**
