### PR TITLE
Feature/patent size dynamic - PST-127

### PR DESCRIPTION
**Pull request by AlbinaMuzafarova**
patent nodes of sizes: 15, 20, 25 px

Note: I am not completely convinced of this change because it's not as dynamic for patents as for the rest of nodes. The constraints posed by checkmarks and arrows lead to definition of specific classes which might make it less appealing.

### CODE REVIEW

**Comment by samuelhuebner** [comment]
For most patents that I encountered it's hard to see the difference in size. Also the markers are a little bit off I think. But other then that I noticed some patents with more connections to be bigger than others

**Comment by samuelhuebner** [comment]
image

**Comment by AlbinaMuzafarova** [comment]
yes, the scaling is only up to 25px. If there are suggestions for a better scaling, i'd be happy to adjust. I think mostly the change is visible when more nodes are added (company, authors). Otherwise, they are pretty much all at 15px

**Review by micahh2 — APPROVED** [review]
Great attention to detail @AlbinaMuzafarova! It looks good.

**Review by icicala — COMMENTED** [review]
Looks great Albina! One point to mention here is about checkmarks that are not centred. What if 
to play :) with colour shades.
1. Option - one-time visite the patent colour become slightly darker, 2 detailed previews strong darker. 
image
2. option - 1 visite the stroke become darker, second the inside color become darker
image

**Comment by icicala** [comment]
> Looks great Albina! One point to mention here is about checkmarks that are not centred. What if to play :) with colour shades.
> 
> 1. Option - one-time visite the patent colour become slightly darker, 2 detailed previews strong darker.
>    image
> 2. option - 1 visite the stroke become darker, second the inside color become darker
>    image

Also, after the patent toggle is off all the nodes comes back to the initial size. 
image

**Comment by AlbinaMuzafarova** [comment]
@icicala the option will color changes can be found in `feature/patent-size-alt` (PR 97). Do you like it better? 

unfortunately, I'm not sure how to get the node links data when they are not active..

**Comment by AlbinaMuzafarova** [comment]
closing this PR since there's little time left to get team's and client's feedback on the changes

**Pull request closed without merging**
