### PR TITLE
(Option A) Hookup patents toggle - PST-145

### PR DESCRIPTION
**Pull request by micahh2**
This is option A, we hook up the toggle so you can actually use it.

### CODE REVIEW

**Review by icicala — COMMENTED** [review]
Danke @micahh2 ! What if we can add a fade toggle button with hook up? and to disable the patent node to be toggle off, in documentation, we can explain it is left for further implementation. 
image

**Comment by samuelhuebner** [comment]
I am not sure if it is an error on my side but on both branches the toggle is now a fixed circle

**Comment by AlbinaMuzafarova** [comment]
@micahh2 could you share a screenshot of what this one looks like? for me both options show up as a circle :(

**Comment by duaakelzi** [comment]
for me also both are just a circle @micahh2

**Comment by micahh2** [comment]
@samuelhuebner Woops. I somehow managed to screw that commit up. It should be working now
image

**Review by AlbinaMuzafarova — APPROVED** [review]
works for me, thank you Micah!

I really like this option: it's a lot easier to go through authors and other nodes without patents. but i'm not sure client will think the same.

**Review by samuelhuebner — APPROVED** [review]
I also prefer this option 👍🏼

**Pull request merged**
