### PR TITLE
 Node highlight and marking restored - PST-160

### PR DESCRIPTION
**Pull request by AlbinaMuzafarova**
nodes should be highlighted correctly again. 

if patent -> receives a mark, else only highlighted

NOTE: @duaakelzi I disabled your load-more button check because the load-more button would not be shown at all for me otherwise. I think I'm on the latest version of main

### CODE REVIEW

**Review by icicala — APPROVED** [review]
@AlbinaMuzafarova Thank You for your bug fix, a very important one for us. 
I have tested and I found a performance issue. On loading, more than 400 nodes, on click on patent or non-patent nodes takes some seconds until the node is highlighted or marked as visited, this creates a feeling of freezing the graph. I suppose this can be the time of searching for the selected node throw the array. Since we removed the load more button this can not be an issue for our demo. Thank you @AlbinaMuzafarova for your contribution.

**Comment by samuelhuebner** [comment]
> @AlbinaMuzafarova Thank You for your bug fix, a very important one for us. I have tested and I found a performance issue. On loading, more than 400 nodes, on click on patent or non-patent nodes takes some seconds until the node is highlighted or marked as visited, this creates a feeling of freezing the graph. I suppose this can be the time of searching for the selected node throw the array. Since we removed the load more button this can not be an issue for our demo. Thank you @AlbinaMuzafarova for your contribution.

I did some research regarding the performance topic when moving from vues rendering to d3. And it simply is the case that with to many nodes active the performance will suffer still. The lagging is caused by the timeout. Javascript is single threaded and since a lot of stuff needs to be done with that many nodes the timeout will take a little bit longer since the event loop is only processed when the main thread is free. So this is not really something we can do anything about

**Review by samuelhuebner — APPROVED** [review]
Works for me. Thank you for fixing the bug @AlbinaMuzafarova

**Comment by icicala** [comment]
> > @AlbinaMuzafarova Thank You for your bug fix, a very important one for us. I have tested and I found a performance issue. On loading, more than 400 nodes, on click on patent or non-patent nodes takes some seconds until the node is highlighted or marked as visited, this creates a feeling of freezing the graph. I suppose this can be the time of searching for the selected node throw the array. Since we removed the load more button this can not be an issue for our demo. Thank you @AlbinaMuzafarova for your contribution.
> 
> I did some research regarding the performance topic when moving from vues rendering to d3. And it simply is the case that with to many nodes active the performance will suffer still. The lagging is caused by the timeout. Javascript is single threaded and since a lot of stuff needs to be done with that many nodes the timeout will take a little bit longer since the event loop is only processed when the main thread is free. So this is not really something we can do anything about @icicala

Thank You @samuelhuebner! As I am new in JS, I didn't know that is a single-threaded language. Good to know!  Solved!

**Review by duaakelzi — APPROVED** [review]
it is fixed , thank you Albina

**Comment by AlbinaMuzafarova** [comment]
to reduce merge conflicts will merge this branch once PR 88 approved

**Pull request merged**
