### PR TITLE
feature(client): show the DetailedPatentView on the result page - PST…

### PR DESCRIPTION
**Pull request by duaakelzi**
…-116

### CODE REVIEW

**Review by micahh2 — APPROVED** [review]
Looks good!

**Review by AlbinaMuzafarova — APPROVED** [review]
works on my side too, thanks Duaa!

**Review by icicala — APPROVED** [review]
Danke Duaa! Works Perfect!

**Review by samuelhuebner — APPROVED** [review]
The detailed view shows up when it's supposed to. Good Job @duaakelzi

**Pull request merged**
