### PR TITLE
Fix performance problems and add highlight of nodes - PST-98, PST-124

### PR DESCRIPTION
**Pull request by samuelhuebner**

### CODE REVIEW

**Comment by samuelhuebner** [comment]
This PR contains the changes @AlbinaMuzafarova added for PST-124, PST-112 and also the performance improvements introduced by moving to d3's rendering (PST-97)

**Review by AlbinaMuzafarova — APPROVED** [review]
works as expected on my side, thanks Samuel!

A note for the team: PST-112 is still in development, so not present here yet.

**Review by icicala — APPROVED** [review]
**WAW! GREAT WORK!** Very impressive! It works smoother and much better. I could add just the gravitation and attraction between the nodes to be a little higher. But this is just a matter of the test. Danke Samu! You are priceless. 
image

**Review by duaakelzi — APPROVED** [review]
thank you Samu and Albina, works fine on my side

**Pull request merged**
