### PR TITLE
refactor(client): Change pin-icon to save-icon - PST-111

### PR DESCRIPTION
**Pull request by icicala**
A simple task that the icon from patent view and detail view is changed to save icon instead of pin icon.

### CODE REVIEW

**Review by micahh2 — APPROVED** [review]
:+1:

**Comment by icicala** [comment]
> 👍
Very hard work:)

**Review by AlbinaMuzafarova — APPROVED** [review]
looks good on my side, thanks Ion! 

(I would have preferred the bookmark icon though since we use it for Saved already. But that's a minor issue)

**Review by samuelhuebner — COMMENTED** [review]
I also think it would be more consistent to use the same icon as the "saved" button. Other than that it works 👍🏼

**Comment by icicala** [comment]
> I also think it would be more consistent to use the same icon as the "saved" button. Other than that it works 👍🏼

Sure! I will fix it in a moment!

**Comment by icicala** [comment]
> I also think it would be more consistent to use the same icon as the "saved" button. Other than that it works 👍🏼

Done! Thx @AlbinaMuzafarova @samuelhuebner @micahh2

**Pull request merged**
