### PR TITLE
fix(client): same height for all buttons - PST-157

### PR DESCRIPTION
**Pull request by duaakelzi**
just adjusted the height, cant be the same width because of the content

### CODE REVIEW

**Review by micahh2 — APPROVED** [review]
This seems to work for me, although FWIW it doesn't handle when the button needs to wrap:

image

**Review by icicala — APPROVED** [review]
Micah noticed this wrapping problem but I think so far the problem is solved. Danke Duaa!

**Comment by duaakelzi** [comment]
yeah i don't have this problem @icicala @micahh2

**Comment by icicala** [comment]
> yeah i don't have this problem @icicala @micahh2

@duaakelzi To be honest our components are not resizable on the smaller screens. I think your solution is ok! Danke!

**Review by AlbinaMuzafarova — COMMENTED** [review]
looks good on my side for Load More, Saved, Saved Item(s), and the back button on the saved page. thanks Duaa!

I'm having same issue as Micah with Start Exploration. Using firefox, if this helps. 

image

**Review by AlbinaMuzafarova — APPROVED** [review]

**Review by samuelhuebner — APPROVED** [review]
👍🏼  @duaakelzi

**Pull request merged**
