### PR TITLE
Add fade effect to loaded results when loading

### PR DESCRIPTION
**Pull request by micahh2**
This PR is very optional. When trying (unsuccessfully) to reproduce PST-147 I realized that perhaps this would look nice so I did it. 

When the loading bar is shown (changing the terms / filters, or loading more) this PR makes the results partially transparent until the loading is done.

Let me know if we should merge it or throw it out!

### CODE REVIEW

**Review by samuelhuebner — APPROVED** [review]
I like the addition @micahh2 👍🏼

**Review by icicala — APPROVED** [review]
I like it! great job! danke @micahh2

**Comment by fiordidoma** [comment]
Pretty neat! Well done @micahh2!

**Review by AlbinaMuzafarova — APPROVED** [review]
i like it too, thanks Micah!

**Review by duaakelzi — APPROVED** [review]
i like it thank you Micah

**Pull request merged**
