### PR TITLE
feat(client): Inform user no results - temp solutions - PST-136

### PR DESCRIPTION
**Pull request by AlbinaMuzafarova**
very basic solution for now: shows error and informs that no results were found.

a more elaborate solution to follow, if there's time left. 

suggestions to test: use spanish with austria (any keyword), or german with "test" keyword

### CODE REVIEW

**Review by samuelhuebner — APPROVED** [review]
Works! thank you @AlbinaMuzafarova

**Review by duaakelzi — APPROVED** [review]
works thank you Albina

**Review by icicala — COMMENTED** [review]
I find the idea with a toast to inform the user a very light and good approach. Instead to have 404 Page Not Found which is more old fashion from my point of view. :)) I push on a temporary branch https://github.com/TPRO-2021/DuckDuckPatent/tree/no-results-filters-warning (the branch will be deleted after you push to the main)
Check it out instead of an Error toast message to have a warning or even info(type of toast) to inform the user about the page not found. I find the error message a little bit concerning the user that have done something wrong. 
image

**Comment by AlbinaMuzafarova** [comment]
@icicala thanks, i didn't know you were working on the issue, otherwise i would not have taken it. 

I don't have a strong opinion on how this case should be handled, so i leave it up to you and the team. 

In my opinion, there's no big difference between no results due to keyword or filter selection. Hence, we should probably be consistent in terms of message shown and use the same message for both cases.

**Comment by samuelhuebner** [comment]
> @icicala thanks, i didn't know you were working on the issue, otherwise i would not have taken it.
> 
> I don't have a strong opinion on how this case should be handled, so i leave it up to you and the team.
> 
> In my opinion, there's no big difference between no results due to keyword or filter selection. Hence, we should probably be consistent in terms of message shown and use the same message for both cases.

@icicala I agree with @AlbinaMuzafarova. Would have made more sense to discuss this with the person doing the task before starting something on your own. 

That said I don't think its a bad idea to distinguish between general and not found errors. So maybe we can combine the content of the modified toast with the behavior @AlbinaMuzafarova introduced.

**Comment by icicala** [comment]
> @icicala thanks, i didn't know you were working on the issue, otherwise, I would not have taken it.
> 
> I don't have a strong opinion on how this case should be handled, so I leave it up to you and the team.
> 
> In my opinion, there's no big difference between no results due to keyword or filter selection. Hence, we should probably be consistent in terms of the message shown and use the same message for both cases.

I haven't worked on your task at all. On reviewing your work I found it necessary at that time to make my proposal how I would like to see it, nothing more. My point of view is the following:  Inserting some keywords and research not found is not an error, that may lead to the user feeling that has done something wrong. I found the message 'not found' kind of info to let the user know to refine his research. As we are leaving in a democracy the majority win, the majority is your side. :))) So we are going to keep the toast how it is.

**Comment by icicala** [comment]
> > @icicala thanks, i didn't know you were working on the issue, otherwise i would not have taken it.
> > I don't have a strong opinion on how this case should be handled, so i leave it up to you and the team.
> > In my opinion, there's no big difference between no results due to keyword or filter selection. Hence, we should probably be consistent in terms of message shown and use the same message for both cases.
> 
> @icicala I agree with @AlbinaMuzafarova. Would have made more sense to discuss this with the person doing the task before starting something on your own.
> 
> That said I don't think its a bad idea to distinguish between general and not found errors. So maybe we can combine the content of the modified toast with the behavior @AlbinaMuzafarova introduced.

@samuelhuebner I have not worked at all on Albina's task. At the end of the day, after you helped me with my task, I wanted to review the work of others(including Albina's work). I played around a bit and I found the warning message(or info) is more appropriate instead of an error. My mistake was to push it on git, I thought others can test to say their opinion. I think I learn the lesson and I will comment only next time. But I didn't take the task of Albina at all, it is not in my interest to do it.

**Review by icicala — APPROVED** [review]

**Comment by AlbinaMuzafarova** [comment]
@icicala I am sorry to have misread your comment - I just wanted to avoid parallel work and would have been happy if you had carried on with this ticket.

I'll try to collect more feedback on monday then.

**Comment by samuelhuebner** [comment]
> > > @icicala thanks, i didn't know you were working on the issue, otherwise i would not have taken it.
> > > I don't have a strong opinion on how this case should be handled, so i leave it up to you and the team.
> > > In my opinion, there's no big difference between no results due to keyword or filter selection. Hence, we should probably be consistent in terms of message shown and use the same message for both cases.
> > 
> > 
> > @icicala I agree with @AlbinaMuzafarova. Would have made more sense to discuss this with the person doing the task before starting something on your own.
> > That said I don't think its a bad idea to distinguish between general and not found errors. So maybe we can combine the content of the modified toast with the behavior @AlbinaMuzafarova introduced.
> 
> @samuelhuebner I have not worked at all on Albina's task. At the end of the day, after you helped me with my task, I wanted to review the work of others(including Albina's work). I played around a bit and I found the warning message(or info) is more appropriate instead of an error. My mistake was to push it on git, I thought others can test to say their opinion. I think I learn the lesson and I will comment only next time. But I didn't take the task of Albina at all, it is not in my interest to do it.

@icicala Alright 👍🏼 But since you already made the change it would be nice do discuss with the team if your extension would be a nice addon. From my point of view it makes sense to differentiate between errors and not found. And it would be sad if we can't use your change because you already removed your branch...

**Comment by icicala** [comment]
> > > > @icicala thanks, i didn't know you were working on the issue, otherwise i would not have taken it.
> > > > I don't have a strong opinion on how this case should be handled, so i leave it up to you and the team.
> > > > In my opinion, there's no big difference between no results due to keyword or filter selection. Hence, we should probably be consistent in terms of message shown and use the same message for both cases.
> > > 
> > > 
> > > @icicala I agree with @AlbinaMuzafarova. Would have made more sense to discuss this with the person doing the task before starting something on your own.
> > > That said I don't think its a bad idea to distinguish between general and not found errors. So maybe we can combine the content of the modified toast with the behavior @AlbinaMuzafarova introduced.
> > 
> > 
> > @samuelhuebner I have not worked at all on Albina's task. At the end of the day, after you helped me with my task, I wanted to review the work of others(including Albina's work). I played around a bit and I found the warning message(or info) is more appropriate instead of an error. My mistake was to push it on git, I thought others can test to say their opinion. I think I learn the lesson and I will comment only next time. But I didn't take the task of Albina at all, it is not in my interest to do it.
> 
> @icicala Alright 👍🏼 But since you already made the change it would be nice to discuss with the team if your extension would be a nice addon. From my point of view, it makes sense to differentiate between errors and not found. And it would be sad if we can't use your change because you already removed your branch...

I removed not to create confusion that I worked on the task. I think You and Albina were right not to differentiate between no results due to keywords and filter selection. I have not taken into consideration the consistency of both cases. Sorry, the late work in the evening affected my vigilance. :))))

**Comment by fiordidoma** [comment]
Good job @AlbinaMuzafarova!

It would be nice if you guys could give your suggestions _before_ the feature has been implemented, maybe in the card description in Jira? This way everyone is more productive, i guess. :-)

**Comment by AlbinaMuzafarova** [comment]
I'll merge this branch for now as it is. In case we have time left in the next sprint to revisit error messages, we should take up the feedback and find an appropriate solution then.

**Pull request merged**
