### PR TITLE
fix(client): save button doesn't disappear in patentPreview - PST-165

### PR DESCRIPTION
**Pull request by duaakelzi**
i realized that something went wrong in patentPreview : the save button doesn't disappear after saving the patent so i fixed this bug

### CODE REVIEW

**Review by samuelhuebner — APPROVED** [review]
Works again 👍🏼  Thank you @duaakelzi

**Review by AlbinaMuzafarova — APPROVED** [review]
looks good, thank you Duaa!

**Review by icicala — APPROVED** [review]
Works great! In another ticket maybe make sense to avoid closing the patent preview by clicking on save.

**Review by micahh2 — APPROVED** [review]
I fixed this  already... looks like the changes got squashed somehow? Anyway, it looks great with the exception that we could make this component really "dumb" (not reading directly from the store). Just change "!isSaved" to "current.showSave" in the template. It's already been calculated.

**Comment by duaakelzi** [comment]
> I fixed this already... looks like the changes got squashed somehow? Anyway, it looks great with the exception that we could make this component really "dumb" (not reading directly from the store). Just change "!isSaved" to "current.showSave" in the template. It's already been calculated.

i changed as you requested

**Pull request merged**
