### PR TITLE
refactor(client): Changed not-found toast - PST-161

### PR DESCRIPTION
**Pull request by icicala**
…the result page - PST-161
In the last meeting with the customer, he pointed out that the error message should be replaced with some info message about result not found. 
I came with two options: 
1. warning toast
2. info toast
Please tell me your opinion and impression. 
image

### CODE REVIEW

**Comment by fiordidoma** [comment]
Warning toast looks better imo.

**Review by samuelhuebner — APPROVED** [review]
I like the warning option 👍🏼 

Maybe we could change the message to something a little bit shorter, e.g. 
"Try modifying your search terms" or something like that.

**Review by duaakelzi — APPROVED** [review]
i like it thank you Ion just like Samu said maybe a shorter message

**Review by AlbinaMuzafarova — APPROVED** [review]
like it too, thanks Ion! 

Maybe the datail could be `Try modifying your filters or search terms` ?

**Comment by icicala** [comment]
> Try modifying your filters or search terms

Thank You @AlbinaMuzafarova for the suggestion. Fit perfectly to our context.

**Comment by icicala** [comment]
> i like it thank you Ion just like Samu said maybe a shorter message

@duaakelzi Solved!

**Comment by icicala** [comment]
> I like the warning option 👍🏼
> 
> Maybe we could change the message to something a little bit shorter, e.g. "Try modifying your search terms" or something like that.

@samuelhuebner I tried to take into consideration Albina's and your suggestion. Since your version is included in Albina's version I selected Albina's. I hope it is fine it.

**Pull request merged**
